name: Black Formatter

on:
  push:
    branches:
      - master
      - devel
  pull_request:
      branches:
        - master
        - devel

jobs:
  blackformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: "buildtest tests scripts --check"

      - name: Check imports with pyflakes
        run: |
          pip install pyflakes
          pyflakes buildtest tests scripts
